name = "fortran-publisher-subscriber"
version = "0.1.0"
license = "MIT"
author = "kiz0329"
maintainer = ""
copyright = "copyright (c) 2026 kiz0329"

[dependencies]
# stdlib = {git ="https://github.com/fortran-lang/stdlib.git", branch = "stdlib-fpm"}

[dev-dependencies]

[install]
library = true